// src/components/parsing/Links.jsx
export default function Links({ data }) {
  if (!data) return null;

  return (
    <div>
      <h2 className="text-xl font-medium">Links</h2>
      <ul>
        {data.map((link, index) => (
          <li key={index}>
            <a href={link.url} target="_blank" rel="noopener noreferrer">
              {link.name} - {link.url_text}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/lib/components/Links.svelte
<script>
  export let data = null;
</script>

{#if data}
  <div>
    <h2 class="text-xl font-medium">Links</h2>
    <ul>
      {#each data as link, index (index)}
        <li>
          <a href={link.url} target="_blank" rel="noopener noreferrer">
            {link.name} - {link.url_text}
          </a>
        </li>
      {/each}
    </ul>
  </div>
{/if}
